### ISSUE TITLE
Fix disappearing icons when center button is clicked too frequently

### ISSUE THREAD

**Issue by estebansotoara** [JustinFincher/JZMultiChoicesCircleButton#1]
Hello,

I liked you library and saw this item in the TO DO list and wanted to give a hand. I made a few validations and the issue is no more, also noticed that the button had a funny behaviour if you manage to tap the center button after selecting one of the options, I validated this case too and prevent tapping while a TouchUpInsideAnimation is running

You can check my fork here: https://github.com/estebansotoara/JZMultiChoicesCircleButton/tree/fastTapIconDisappear and if you like it I can make a PR

**Comment by JustinFincher** [comment]
Hi estebansotoara :-)
I cloned your branch and ran it on simulator. It seems the small button icon still disappear when clicking too frequently (0.05 sec).
The reason is that `TouchUpInsideAnimation` last at least 1 sec, but `TouchUpAnimation` can be called twice in 0.1 sec, so set `isPerformingTouchUpInsideAnimation = NO;` in `TouchUpInsideAnimation` will not help solving the problem, but in `TouchUpAnimation` will do.  
in  `TouchUpInsideAnimation`  

```
[CATransaction begin];
    //__weak JZMultiChoicesCircleButton *weakSelf = self;
    [CATransaction setCompletionBlock:^
     {
         //weakSelf.isPerformingTouchUpInsideAnimation = NO;
     }];
    [SmallButton.layer addAnimation:animGroup forKey:@"ButtonScaleAnimation"];
    [CATransaction commit];

```

in  `TouchUpAnimation`  

```
    [SmallButton setImage:IconImage forState:UIControlStateNormal];
    [UIView animateWithDuration:0.1 animations:^(void){ [SmallButton.imageView setAlpha:1.0]; } completion:^(BOOL finished)
    {
        if (finished)
        {
            [SmallButton setImage:IconImage forState:UIControlStateNormal];
            self.isPerformingTouchUpInsideAnimation = NO;
        }
    }];
```

I think that will eventually solve the problem, you can test it and if that really works, please change codes in your branch and I will merge it.  
(Also I think you can change the BOOL name `isPerformingTouchUpInsideAnimation` to `isPerformingTouchUpAnimation`, that will help people understand what this BOOL really means  )
Thanks for your help and welcome to give a PR ^_^

**Comment by estebansotoara** [comment]
Hi, 
Sorry about that, I tested on device and didn't tap fast enough to see it, only saw the disappearing options, I managed to solve the issue validating the `finished` attribute of animations, no need to move `isPerformingTouchUpInsideAnimation` and as it was used for the "tap and keep pressed small button after select an option" glitch it was good thing that didn't have to be changed, I'll do the PR then
